// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManagement.Infrastructure.EFCore;

#nullable disable

namespace ProjectManagement.Infrastructure.EFCore.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjectManagement.Domain.CityAgg.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 8, 1, 0, 59, 54, 974, DateTimeKind.Local).AddTicks(4705),
                            IsDeleted = false,
                            Name = "تهران",
                            Position = "مرکز",
                            ProvinceId = 1,
                            Scope = 270
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 8, 1, 0, 59, 54, 974, DateTimeKind.Local).AddTicks(4725),
                            IsDeleted = false,
                            Name = "ارومیه",
                            Position = "شمال غرب",
                            ProvinceId = 2,
                            Scope = 65
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 8, 1, 0, 59, 54, 974, DateTimeKind.Local).AddTicks(4728),
                            IsDeleted = false,
                            Name = "تبریز",
                            Position = "شمال غرب",
                            ProvinceId = 3,
                            Scope = 145
                        });
                });

            modelBuilder.Entity("ProjectManagement.Domain.ProvinceAgg.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Provinces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 8, 1, 0, 59, 54, 974, DateTimeKind.Local).AddTicks(4096),
                            IsDeleted = false,
                            Name = "تهران",
                            Position = "مرکز",
                            Scope = 1500
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 8, 1, 0, 59, 54, 974, DateTimeKind.Local).AddTicks(4240),
                            IsDeleted = false,
                            Name = "آذربایجان غربی",
                            Position = "شمال غرب",
                            Scope = 2200
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 8, 1, 0, 59, 54, 974, DateTimeKind.Local).AddTicks(4251),
                            IsDeleted = false,
                            Name = "آذربایجان شرقی",
                            Position = "شمال غرب",
                            Scope = 1900
                        });
                });

            modelBuilder.Entity("ProjectManagement.Domain.WeatherAgg.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentTemperature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralCondition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .IsUnique();

                    b.ToTable("Weathers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CreationDate = new DateTime(2022, 8, 1, 0, 59, 54, 974, DateTimeKind.Local).AddTicks(4514),
                            CurrentTemperature = "+32",
                            GeneralCondition = "گرم خشک",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            CreationDate = new DateTime(2022, 8, 1, 0, 59, 54, 974, DateTimeKind.Local).AddTicks(4526),
                            CurrentTemperature = "+22",
                            GeneralCondition = "گرم مرطوب",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            CreationDate = new DateTime(2022, 8, 1, 0, 59, 54, 974, DateTimeKind.Local).AddTicks(4534),
                            CurrentTemperature = "+21",
                            GeneralCondition = "گرم مرطوب",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ProjectManagement.Domain.CityAgg.City", b =>
                {
                    b.HasOne("ProjectManagement.Domain.ProvinceAgg.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ProjectManagement.Domain.WeatherAgg.Weather", b =>
                {
                    b.HasOne("ProjectManagement.Domain.CityAgg.City", "City")
                        .WithOne("Weather")
                        .HasForeignKey("ProjectManagement.Domain.WeatherAgg.Weather", "CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("ProjectManagement.Domain.CityAgg.City", b =>
                {
                    b.Navigation("Weather")
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagement.Domain.ProvinceAgg.Province", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
